In [3]:
import numpy as np

### 1.Create an array of 10 tens

In [15]:
arr1 = np.ones(10) * 10
print(arr1)

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


### 2.Create an array of all the odd integers from 100 to 200

In [16]:
arr2 = np.arange(101,200,2)
print(arr2)

[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129 131 133 135
 137 139 141 143 145 147 149 151 153 155 157 159 161 163 165 167 169 171
 173 175 177 179 181 183 185 187 189 191 193 195 197 199]


### 3.Create a 3x3 identity matrix

In [6]:
mat1 = np.identity(3)
print(mat1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 4.write a code that gives the output given below

In [7]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### 5.Create a 4X4 matrix with values starting from 0

In [18]:
mat2 = np.arange(16).reshape(4,4)
print(mat2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### 6.Use NumPy to generate an array of 9 random numbers sampled from a standard normal distribution

In [19]:
arr3 = np.random.randn(9)
print(arr3)

[-0.44711341 -0.34863591 -0.11152512 -0.31621416 -1.41519307  0.95639555
 -0.01555871  1.39151411 -1.37772182]


In [10]:
j=np.arange(12,24).reshape(3,4)
j

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### 7.Get the standard deviation of the values in matrix

In [11]:
std_deviation = np.std(j)
print(std_deviation)

3.452052529534663


### 8.Get the sum of all the columns in mat

In [12]:
np.sum(j,axis=0)

array([48, 51, 54, 57])

### 9.write a code that gives the following output given below.

In [13]:
j[:,1:2]

array([[13],
       [17],
       [21]])

### 10.Get the sum of all the values in mat

In [14]:
np.sum(j)

210